spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/devDB
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/devDB
    user: postgres
    password: postgres
    locations: classpath:/db/migration
  jpa:
    show-sql: true